### ISSUE TITLE
"hyphen" should not be considered as an invalid character in field names

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#3]
WARNING: [Field: date-retrieved, Value: date-retrieved: 2013-01-16, Message: Field name contains invalid characters: '-': line ignored.]

**Comment by pombredanne** [comment]
@chinyeungli This is for field names only and by design in the about spec at http://www.dejacode.org/about_spec_v0.8.0.html . The reason is that several programming languages such as Ruby, Python, Java or PHP do not allow hyphens in variable names. This leave the possibility to map field names to variables of an object if needed. Use an underscore instead. Unless you have strong feelings about this, I would close this ticket.

**Comment by chinyeungli** [comment]
@pombredanne closing it.
